name: Lighthouse CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Install LHCI
        run: npm install -g @lhci/cli@0.14.x
      - name: Run Lighthouse CI
        run: lhci autorun --config=./lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}